[pyrogram]
api_id = 22941360
api_hash = "cd8fb83bbf47a7e373b650bd338ad3d6"
session_string = "BQFeDrAAuYPOQyexdbtPmpJxx3LZ_ZyDZ8MkUrF6iZ480f4-igB2rjQZd9R9ufmIKWCIKMiyO0H__TMtWJo07C7wNJYUYbkWwS1-0DIZ8lyG2SmIZgeIgTgeFvQEqW8jpsNV3EvT_NBfgo4fwJV87Uu2kW3qGS4cuAijOeeD7MnXTCi33S4EoZOgIz5KA7txEwHOAsLkhM4tOMpyfsCB6L_-MtQFu1gJ1FI8yD_BSCNoQBty_oeoxGNtUB9okXVIA2lCDZ7g_bKp4F_jD9bpHOJ0kynz_tmoXJ5O_FKmaGmLZI0MmX0_PbKJmDBypIbHpJCkFYMufrvM7moAe2UxPDrOitoO_QAAAAGGtoTVAA"
[[chats]]
from = -1001636189933
to = -1001913832996
