[pyrogram]
api_id = 22941360
api_hash = "cd8fb83bbf47a7e373b650bd338ad3d6"
session_string = "BQFeDrAAKm-usY0FKWvKawwnCQiNmmFCw3Gks84V6jvG__VtOt1bZdukB2y--k7l_ylfWxTkM68vG9q7HhvrvKi1L5d8yl5wX8a7YUWofLMAreX5F6oVZ-pqiyYafKM6CklFGXvSR4sWSdVYU3fKRe_o8GKjAvHbNQJ705EcMeUn4mqOI63yuWTexy_PRoTLV5AqC9N_vUCtqEDvhaWMZ1eEwCrufDTKyYpnkp8dG2x-inep7nr3_DEFaq3Jmdj41xhzsJy3UQIeLDDp_LVs-N2EkKyVfPvonheXKdrb96UAizKItyDXXGsgIGu7brIWs8JQO4QmJsQlABFYuq3IWf6eJuX9BQAAAAGGtoTVAA"
[[chats]]
from = -1001636189933
to = -1001913832996
